<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ChronoFall.CharacterPresentation/ChronoFall.CharacterPresentation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ChronoFall.CharacterCooker" />
    <InternalsVisibleTo Include="ChronoFall.StaticMeshCooker" />
  </ItemGroup>
</Project>
