<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ChronoFall.CharacterExperiment.SimpleMesh/ChronoFall.CharacterExperiment.SimpleMesh.csproj" />
    <ProjectReference Include="../../src/ChronoFall.CharacterPresentation.Cooking/ChronoFall.CharacterPresentation.Cooking.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ChronoFall.CharacterCooker.Tests" />
  </ItemGroup>
</Project>
