<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ChronoFallBox3DEffectiveRuntimeIdentifier Condition="'$(RuntimeIdentifier)' != ''">$(RuntimeIdentifier)</ChronoFallBox3DEffectiveRuntimeIdentifier>
    <ChronoFallBox3DEffectiveRuntimeIdentifier Condition="'$(ChronoFallBox3DEffectiveRuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</ChronoFallBox3DEffectiveRuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ChronoFall.Box3D.Bindings/ChronoFall.Box3D.Bindings.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(ChronoFallBox3DEffectiveRuntimeIdentifier)' == 'osx-arm64'">
    <None Include="../../thirdparty/artifacts/box3d/osx-arm64/lib/libbox3d.dylib" CopyToOutputDirectory="PreserveNewest" TargetPath="runtimes/osx-arm64/native/libbox3d.dylib" />
  </ItemGroup>
  <ItemGroup Condition="'$(ChronoFallBox3DEffectiveRuntimeIdentifier)' == 'linux-x64'">
    <None Include="../../thirdparty/artifacts/box3d/linux-x64/lib/libbox3d.so" CopyToOutputDirectory="PreserveNewest" TargetPath="runtimes/linux-x64/native/libbox3d.so" />
  </ItemGroup>
</Project>
