<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="ChronoFall.CharacterPresentation" />
    <Using Include="ChronoFall.CharacterPresentation.Cooking" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../tools/ChronoFall.StaticMeshCooker/ChronoFall.StaticMeshCooker.csproj" />
    <ProjectReference Include="../../src/ChronoFall.CharacterPresentation.Cooking/ChronoFall.CharacterPresentation.Cooking.csproj" />
  </ItemGroup>
</Project>
