<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ChronoFall.Box3D/ChronoFall.Box3D.csproj" />
    <ProjectReference Include="../../src/ChronoFall.Box3D.Bindings/ChronoFall.Box3D.Bindings.csproj" />
  </ItemGroup>
</Project>
